/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
AssetsRes._();
  static const String PLUGIN_NAME = 'walletium';
  static const String PLUGIN_VERSION = '1.1.0+2';
  static const String APPLE_APP_SITE_ASSOCIATION = 'assets/deep_link/apple-app-site-association';
  static const String EMPTY_ANIMATION = 'assets/empty_animation.json';
  static const String DRAWER_BG = 'assets/images/bg/drawer_bg.svg';
  static const String SIGN_IN_BG = 'assets/images/bg/sign-in-bg.svg';
  static const String CONFIRM = 'assets/images/others/confirm.svg';
  static const String CONGRATULATIONS = 'assets/images/others/congratulations.svg';
  static const String FORGOT_PASSWORD = 'assets/images/others/forgot-password.svg';
}
